name = "EasyConfig"
uuid = "acab07b0-f158-46d4-8913-50acef6d41fe"
authors = ["joshday <emailjoshday@gmail.com>"]
version = "0.1.16"

[deps]
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
StructTypes = "856f2bd8-1eba-4b0a-8007-ebc267875bd4"

[compat]
JSON3 = "1.4.0"
OrderedCollections = "1.3.2"
StructTypes = "1.1.0"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
